### ISSUE TITLE
Solution for old packages using babel-runtime

### ISSUE THREAD

**Issue by mknet** [babel/babel-bridge#4]
I got the issue that I want to use the package `migrate-mongoose`.
Since it's a little dated by now it required some modules of `babel-runtime` in its transpiled version and causes a conflict with my `.babelrc` using the latest presets:

The known `Requires Babel "^7.0.0-0", but was loaded with "6.26.3"`...

Do you think it's a good idea to introduce a bridge for babel_runtime, as well? I could support you setting it up.

**Comment by mknet** [comment]
I solved my concrete issue by using package `migrate-mongoose-babel-7`.
But a runtime bridge still could be a good idea, eh?

**Comment by escapedcat** [comment]
[`"@babel/runtime": "7.0.0-beta.55"` exists](https://github.com/babel/babel/tree/master/packages/babel-runtime) and replaced the old `babel-runtime` in my project quite well. Not sure if this helps in your case.

**Comment by loganfsmyth** [comment]
@mknet If you're having issues I'd recommend raising them in the main Babel support channels. This repo isn't a good place for questions.
