### ISSUE TITLE
babel-core@^7.0.0-0 should be babel-core@^7.0.0-bridge.0

### ISSUE THREAD

**Issue by CharlesStover** [babel/babel-bridge#5]
The package name is incorrect in this documentation, as well as in the `jest` documentation.

There is no package tagged 7.0.0-0, and the 7.0.0-beta packages are incompatible. Installing 7.0.0-0 will simply prompt the user for which package they want (at least in yarn), and `bridge.0` is the only valid package for this use case.

**Comment by loganfsmyth** [comment]
> The package name is incorrect

What name, and which documentation?

> There is no package tagged 7.0.0-0.

`^7.0.0-0` is a semver version range that includes `babel-core@^7.0.0-bridge.0` as the most recent version.

**Comment by CharlesStover** [comment]
My PR updates the documentation in question.
The semvar does not accurately find the bridge package.
I ran into this while trying to install `jest` with Babel 7.
![image](https://user-images.githubusercontent.com/343837/42958371-f9e20fb8-8b4a-11e8-9ebf-7f5883f4be32.png)

I incorrectly chose a beta version thinking that any 7.0.0 would work. They do not work. When I chose bridge.0, however, the problem was resolved.

**Comment by loganfsmyth** [comment]
Hmm, that seems like a Yarn bug. That's frustrating.

**Comment by loganfsmyth** [comment]
Actually I guess bug isn't the right descriptor. Just an unfortunate side-effect of their behavior of displaying options.

**Comment by CharlesStover** [comment]
Is this PR not an accurate fix?

As mentioned, the `7.0.0-beta#` builds do not fix this issues that `-bridge.0` does, so it seems like the semvar should include bridge.

**Comment by stern-shawn** [comment]
+1 for accepting the update.

The team I'm working on is a stickler for having exact versions in `package.json` instead of semver ranges, and the only non-breaking way of listing the package version (at least with Yarn, untested with npm) is `"babel-core": "7.0.0-bridge.0"`.

**Comment by CharlesStover** [comment]
This has been open for a while, with a PR as well. Any news on it being merged? @loganfsmyth @hulkish

**Comment by tricoder42** [comment]
This seems to be `yarn` issue. I'm using `1.9.2` and it works fine:

```
$ yarn add --dev babel-core@^7.0.0-0   
                                                                                                                                   
yarn add v1.9.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ babel-core@7.0.0-bridge.0
info All dependencies
└─ babel-core@7.0.0-bridge.0
   Done in 0.58s.
```

This warning is weird, though:

```
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
```

**Comment by tricoder42** [comment]
I'm on Mac. I have no problem installing package, but I can't get rid of warning. I'm just reporting how it works for me. I never use prereleases with semver so I don't know how the version range works in this case.
